# Generated by Django 4.0 on 2023-08-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
