# Generated by Django 4.0 on 2023-07-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(max_length=245),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
