# Generated by Django 4.0 on 2023-07-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0002_alter_person_branch_alter_person_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='account',
        ),
        migrations.AddField(
            model_name='person',
            name='color',
            field=models.CharField(choices=[('sa', 'Saving Account'), ('ca', 'Current Account')], default='qwer', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='person',
            name='material',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reduction.district')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reduction.branch'),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reduction.district'),
        ),
    ]
