# Generated by Django 4.0 on 2023-07-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0003_district_remove_person_account_person_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='color',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='material',
            new_name='cheque_book',
        ),
        migrations.AddField(
            model_name='person',
            name='credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='debit_card',
            field=models.BooleanField(default=False),
        ),
    ]
